---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-lts-2.18
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm --version

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: W+Rd93/PCfsCFxEhsp3F9thwBfOomf149DtgzrpPfGkFSaAiUg3viFi4A/Qna50hgWTyqIZB+cF28mXXw6NZBc5WjzEXvd0jmfT7/Dz17gdGNyOwtgZLgjhCeipniWeLMCfiJ0rseHmzTmafqTpOM9uRzufywX8E5X3/RAvXVAn5jRi2WT2Lg1vpZiXyGy/iCTcfp+hrPmF01xF5ibzDkY3DKBe+a0l4Q4n6H2s1qHdXIRqRmyHWaQZzjlsyeWYwSLX07zd2gIm7Or47HbXiw/zWKseASwI02D2aafmjUFrYpEF0d2CHobSWsrnoFmgzVYw1I6NJ6vuLCGKbA5VJES5IWK5qAbw9EGD6qCPudyqPUKB2s4N0C+NiTLoiK/BCU7eMRkzPOU0smENliz4dsw36rCMUY7FqOZFaxs4+CP+90pRMTXNXBwtZB8YraFdBBh/8KIB53TyfpUw7C1W3Q+zHMzuOi8K5Wa3M5yhEsWdMEzTwfvNBYzxjlXMhTU12CURP02hHQHJuGMW5A7XTVEVWSZECOo8+Wo6EH8oXXNBlj+JzudJB8qmd5MGyN81m2VoTpJ9toumg7I9xaTdNZshOr9jXCkxHAQBObpO8KfcFnLeS68tAsNYtPst0uEdEeGPs8KWg18lcVcg0LY37VBefDWBOynpvkh0+sNTotP8=
  on:
    tags: true
    repo: simplabs/ember-classy-computed

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never

script:
  - npm run lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
